Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu1804"
  
  config.vm.provider "hyperv"
  
  config.vm.provider "hyperv" do |h|
      h.memory = "2048"
	  h.enable_virtualization_extensions = true
	  h.linked_clone = true
   end

  config.vm.provision "shell", path: "scripts/install.sh" , privileged: true
  
end
